### ISSUE TITLE
[Feature] Update env vars rendered in profiles.yml

### ISSUE THREAD

**Issue by vymaker** [tomasfarias/airflow-dbt-python#88]
Wondering if airflow-dbt-python supports env variables in profiles.yml? If yes, how can I pass it to dag? If no, is there any workaround until the functionality becomes available?

```
<profile_name>:
  outputs:
    <source>:
      database: "{{ env_var('DBT_ENV_SECRET_DATABASE') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      schema: "{{ env_var('DBT_ENV_SECRET_SCHEMA') }}"
      threads: "{{ env_var('DBT_THREADS') }}"
      type: <type>
      user: "{{ env_var('USER_NAME') }}_{{ env_var('ENV_NAME') }}"
  target: <source>
```

```
DBT_ENV = {
    "dbt_host": dbt_host,
    "dbt_port": dbt_port,
    "dbt_dbname": dbt_dbname,
    "dbt_user": dbt_user,
    "dbt_password": dbt_password,
    "dbt_schema": dbt_schema,
}
```

Something like this?
```
 dbt_run = DbtRunOperator(
         task_id="dbt_run",
         env=DBT_ENV,
     )
```

BTW, do we need to define dbt_bin in MWAA?
```
dbt_bin="/usr/local/airflow/.local/bin/dbt",
```
